/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/untitled.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model() {
  const { nodes, materials } = useGLTF("/dungeon.glb");
  return (
    <group dispose={null}>
      <mesh geometry={nodes.crate.geometry} material={materials.brown}>
        <meshStandardMaterial color="red" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/dungeon.glb");
