/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/untitled.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model() {
  const { nodes, materials } = useGLTF("/untitled.glb");
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload("/untitled.glb");
